### ISSUE TITLE
How can I store make-config -r output to a file?

### ISSUE THREAD

**Issue by yoichi** [stevearc/pypicloud-docker#12]
I want to generate pypicloud config file for docker into current directory.
I did:

```
$ docker run -it --rm -v $(pwd):/out stevearc/pypicloud make-config -r /out/config.ini
```

then it prints config to stdout.

NOTE: When I execute without '-r' option, it store result to a file, but the content is not for docker.

Thanks in advance.

**Comment by stevearc** [comment]
Use stdout redirection `docker run -it --rm stevearc/pypicloud make-config -r > config.ini`

**Comment by yoichi** [comment]
It doesn't work since redirect stdout will send prompts ("Where do you want to store your packages?" etc) to file too.
Why can't we use outfile option with docker image?

**Comment by stevearc** [comment]
Ah, yeah I remember doing this. It was because I thought it would be easier for people to copy/paste than mess with docker mounting directories. I'll make this behavior better in the next version, but in the meantime you can bypass it with
`docker run -it --rm -v $(pwd):/out stevearc/pypicloud /env/bin/ppc-make-config -r /out/config.ini`

**Comment by yoichi** [comment]
Works perfectly! Thanks for your help.
